<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class SampleProductsSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name'        => 'Aceite sintético 5W-30',
                'description' => 'Aceite de motor sintético de alta calidad. Recomendado para vehículos modernos.',
                'sku'         => 'ACE-5W30-4L',
                'category'    => 'oil',
                'price'       => 28.50,
                'cost'        => 18.00,
                'stock_quantity' => 25,
                'min_stock_alert' => 5,
                'unit'        => 'liter',
                'is_active'   => true,
            ],
            [
                'name'        => 'Filtro de aceite universal',
                'description' => 'Filtro de aceite de alta eficiencia compatible con la mayoría de vehículos.',
                'sku'         => 'FIL-ACE-UNI',
                'category'    => 'filter',
                'price'       => 12.00,
                'cost'        => 6.50,
                'stock_quantity' => 40,
                'min_stock_alert' => 10,
                'unit'        => 'piece',
                'is_active'   => true,
            ],
            [
                'name'        => 'Filtro de aire',
                'description' => 'Filtro de aire de alto rendimiento. Mejora la eficiencia del motor.',
                'sku'         => 'FIL-AIR-STD',
                'category'    => 'filter',
                'price'       => 15.00,
                'cost'        => 8.00,
                'stock_quantity' => 35,
                'min_stock_alert' => 8,
                'unit'        => 'piece',
                'is_active'   => true,
            ],
            [
                'name'        => 'Pastillas de freno cerámicas',
                'description' => 'Set de pastillas de freno cerámicas para eje delantero.',
                'sku'         => 'FRE-PAD-CER',
                'category'    => 'brake',
                'price'       => 45.00,
                'cost'        => 25.00,
                'stock_quantity' => 20,
                'min_stock_alert' => 5,
                'unit'        => 'set',
                'is_active'   => true,
            ],
            [
                'name'        => 'Disco de freno ventilado',
                'description' => 'Disco de freno ventilado de alta calidad.',
                'sku'         => 'FRE-DIS-VEN',
                'category'    => 'brake',
                'price'       => 55.00,
                'cost'        => 32.00,
                'stock_quantity' => 15,
                'min_stock_alert' => 4,
                'unit'        => 'piece',
                'is_active'   => true,
            ],
            [
                'name'        => 'Batería 12V 60Ah',
                'description' => 'Batería libre de mantenimiento para vehículos compactos y medianos.',
                'sku'         => 'BAT-12V-60',
                'category'    => 'battery',
                'price'       => 85.00,
                'cost'        => 55.00,
                'stock_quantity' => 10,
                'min_stock_alert' => 3,
                'unit'        => 'piece',
                'is_active'   => true,
            ],
            [
                'name'        => 'Batería AGM 12V 70Ah',
                'description' => 'Batería AGM de ciclo profundo para alto consumo eléctrico.',
                'sku'         => 'BAT-AGM-70',
                'category'    => 'battery',
                'price'       => 140.00,
                'cost'        => 90.00,
                'stock_quantity' => 8,
                'min_stock_alert' => 2,
                'unit'        => 'piece',
                'is_active'   => true,
            ],
            [
                'name'        => 'Escáner OBD2 profesional',
                'description' => 'Escáner de diagnóstico OBD2 de grado profesional.',
                'sku'         => 'SCN-OBD2-PRO',
                'category'    => 'scan_tool',
                'price'       => 120.00,
                'cost'        => 75.00,
                'stock_quantity' => 5,
                'min_stock_alert' => 2,
                'unit'        => 'piece',
                'is_active'   => true,
            ],
            [
                'name'        => 'Multímetro digital',
                'description' => 'Multímetro digital para diagnóstico eléctrico automotriz.',
                'sku'         => 'ELE-MUL-DIG',
                'category'    => 'electrical',
                'price'       => 35.00,
                'cost'        => 18.00,
                'stock_quantity' => 12,
                'min_stock_alert' => 3,
                'unit'        => 'piece',
                'is_active'   => true,
            ],
            [
                'name'        => 'Cable de batería (juego)',
                'description' => 'Juego de cables de batería para arranque auxiliar. 3 metros.',
                'sku'         => 'ELE-CAB-BAT',
                'category'    => 'electrical',
                'price'       => 22.00,
                'cost'        => 12.00,
                'stock_quantity' => 18,
                'min_stock_alert' => 5,
                'unit'        => 'kit',
                'is_active'   => true,
            ],
            [
                'name'        => 'Kit de herramientas básico',
                'description' => 'Kit de 45 piezas para mantenimiento automotriz básico.',
                'sku'         => 'ACC-KIT-45P',
                'category'    => 'accessory',
                'price'       => 65.00,
                'cost'        => 38.00,
                'stock_quantity' => 8,
                'min_stock_alert' => 2,
                'unit'        => 'kit',
                'is_active'   => true,
            ],
            [
                'name'        => 'Refrigerante verde',
                'description' => 'Refrigerante concentrado. Protege contra congelación y corrosión.',
                'sku'         => 'OTH-COL-GRN',
                'category'    => 'other',
                'price'       => 8.50,
                'cost'        => 4.00,
                'stock_quantity' => 50,
                'min_stock_alert' => 15,
                'unit'        => 'liter',
                'is_active'   => true,
            ],
            [
                'name'        => 'Líquido de frenos DOT4',
                'description' => 'Líquido de frenos de alto rendimiento DOT4.',
                'sku'         => 'OTH-FRE-DOT4',
                'category'    => 'other',
                'price'       => 6.00,
                'cost'        => 3.00,
                'stock_quantity' => 60,
                'min_stock_alert' => 15,
                'unit'        => 'liter',
                'is_active'   => true,
            ],
            [
                'name'        => 'Bujía de encendido iridium',
                'description' => 'Bujía con electrodo de iridium. Mayor vida útil y mejor combustión.',
                'sku'         => 'OTH-BUJ-IRD',
                'category'    => 'other',
                'price'       => 12.00,
                'cost'        => 7.00,
                'stock_quantity' => 100,
                'min_stock_alert' => 25,
                'unit'        => 'piece',
                'is_active'   => true,
            ],
            [
                'name'        => 'Correa de distribución',
                'description' => 'Correa de distribución de alta resistencia.',
                'sku'         => 'OTH-COR-DIST',
                'category'    => 'other',
                'price'       => 38.00,
                'cost'        => 20.00,
                'stock_quantity' => 12,
                'min_stock_alert' => 3,
                'unit'        => 'piece',
                'is_active'   => true,
            ],
        ];

        foreach ($products as $productData) {
            Product::firstOrCreate(
                ['sku' => $productData['sku']],
                $productData
            );
        }

        $this->command->info(count($products) . ' sample products seeded successfully.');
    }
}
